# Build all branches, *including* gh-pages:
branches:
  only:
  - gh-pages
  - master
language: ruby
sudo: false
rvm:
- 2.3.1
install:
- bundle install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: gh-pages
  on:
    branch: master
