# Site
title:              micbon blog
bio:                'personal space for sharing my latest interests.'
description:        "this blog is my personal space for sharing my latest interests."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
# background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_CA
url:                https://blog.micbon.com/
# url:                http://localhost:4000/
author:             "Michael J. Moon"

# Use collections dir
collections_dir: collections
collections:
    menu:
        permalink: /:name
        output: true
    notes:
        permalink: /:categories/:title
        output: true
    courses:
        permalink: /:name
        output: true
    awards:
        ouput: false
    educations:
        ouput: false
    employments:
        ouput: false
    projects:
        ouput: false
    publications:
        ouput: false
    presentations:
        ouput: false
    teachings:
        ouput: false
    skills:
        ouput: false

# Jekyll
permalink:          /:categories/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   micbon-blog

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              micbon.site@gmail.com
github-url:         mjmoon
linkedin:           mjmoon
instagram:          micbonmoon
# twitter:            mjhmoon
# facebook:           username
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#xing:              username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
# steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
plugins:
    - jekyll-paginate-v2
    - jekyll-mentions
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude:
    - README.md
    - Gemfile
    - Gemfile.lock
    - node_modules
    - gulpfile.js
    - package.json
    - _site
    - src
    - vendor
    - LICENSE
    - Rakefile
