# contact email
email: michael.jongho.moon@gmail.com

# Social settings
social:
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/mjmoon/', label: 'LinkedIn'}
- {icon: 'github', link: 'https://www.github.com/mjmoon', label: 'GitHub'}
- {icon: 'rss-square', link: 'feed.xml', label: 'Feed'}

# texts
sharing_button_prompt: Share

# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'https-lenpaul-github-io-lagrange'
