# contact email
email: michael.jongho.moon@gmail.com

# Social settings
social:
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/mjmoon/', label: 'LinkedIn'}
- {icon: 'github', link: 'https://www.github.com/mjmoon', label: 'GitHub'}
- {icon: 'instagram', link: 'https://www.instagram.com/micbonmoon/', label: 'Instagram'}
- {icon: 'twitter', link: 'https://twitter.com/mjhmoon', label: 'Twitter'}
- {icon: 'rss-square', link: 'feed.xml', label: 'Feed'}

# texts
sharing_button_prompt: Share
tag_list_promt: Tags
related_posts: Related posts

# Change to true for Disqus comments
disqus:
  comments: true
